elementary:
  outputs:
    default:
      type: "snowflake"
      account: "FGTPTGU-LR92863"
      user: "guserrl2"
      password: "151516G1.,ul"
      role: None
      warehouse: "PC_DBT_WH"
      database: "PC_DBT_DB"
      schema: "DBT_GDBT_elementary"
      threads: 4