elementary:
  target: dev
  outputs:
    dev:
      type: "snowflake"
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4

default:
  target: dev
  outputs:
    dev:
      type: "snowflake"
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "DBT_GDBT"
      threads: 4