version: 2

models:
  - name: stg_customer
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
  - name: stg_line_item
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
  - name: stg_nation
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
  - name: stg_orders
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
  - name: stg_part
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
  - name: stg_region
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
  - name: stg_supplier
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
  - name: stg_partsupp
    config:
      elementary:
        timestamp_column: "load_data"
    tests:
       - elementary.volume_anomalies:
          time_bucket:
            period: hour
            count: 1
