# version: 2

# models:
#   - name: s_supplier
#     description: "Satelite de supplier"
#     columns:
#       - name: h_supplier_haskey
#         description: "Clave primaria en formato md5"
#         tests:
#           - unique
#           - not_null
#       - name: has_diff
#         description: "Has generado a partir de nombre name address phone comment"
#       - name: load_record
#         description: "Tiempo de carga del dato"
#         tests:
#           - test_fecha
#       #- name: is_active
#       #  description: "Indica si customer sigue activo, 0=false 1=true"
#       #  tests:
#       #    - is_active
#       - name: last_modified
#         description: "Ultima fecha de modificacion"
#       - name: source
#         description: "Lugar de donde cargo el dato"
#       - name: suppkey
#         description: "Clave de supplier"
#         tests:
#           - unique
#           - not_null
#       - name: comment
#         description: "Comentarios adicionales"
#       - name: name
#         description: "Nombre de supplier"
#         tests:
#           - not_null
#       - name: address
#         description: "Direccion de supplier"
#       - name: phone
#         description: "Teelfono de supplier"
#   - name: h_supplier
#     columns:
#       - name: h_supplier_haskey
#         description: "Clave primaria en formato md5"
#         tests:
#           - unique
#           - not_null
#       - name: suppkey
#         description: "Clave de supplier"
#         tests:
#           - unique
#           - not_null
#       - name: load_record
#         tests:
#           - test_fecha
#       - name: source
#         description: "Lugar de donde cargo el dato"
