version: 2

models:
  - name: stg_hist_customer
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"
  - name: stg_hist_line_item
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
      elementary:
        timestamp_column: "load_data"
    tests:
      - elementary.dimension_anomalies:
          dimensions: 
            - l_line_item_haskey
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"
  - name: stg_hist_nation
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"
  - name: stg_hist_orders
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
      elementary:
        timestamp_column: "load_data"
    tests:
      - elementary.dimension_anomalies:
          dimensions: 
            - orderstatus
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"
  - name: stg_hist_part
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"
  - name: stg_hist_partsupp
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
      elementary:
        timestamp_column: "load_data"
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"
  - name: stg_hist_region
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"
  - name: stg_hist_supplier
    config:
      full_refresh: false
      materialized: incremental
      incremental_strategy: append
    tetss:
      - elementary.freshness_anomalies:
          timestamp_column: "load_data"